// 愛知県尾張地区 高校進学データベース（公立・私立 / 最上位〜最下位・内申オール2〜オール1クラスまで完全網羅）
// 各校の個別詳細ページURL、部活動規定、制服、2026-2027年最新イベント日程付き

const schoolsData = [
  {
    "rank": "S+",
    "rankClass": "rank-S-plus",
    "name": "旭丘高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市東区出来町",
    "group": "尾張1群 Aグループ",
    "score": "43〜45",
    "deviation": "71",
    "uniform": "私服",
    "uniformDetail": "完全私服通学（式典用の標準服あり・服装自由）",
    "clubPolicy": "自由（任意）",
    "clubDetail": "完全自由加入。兼部する生徒や外部活動・学外研究に打ち込む生徒も多数。",
    "features": "県内公立トップの歴史と実績。「自由と規律」を信条とし校則がほぼ皆無。美術科も併設。",
    "results": "東京大・京都大・名古屋大（毎年約100名）・国公立医学部に圧倒的な実績。",
    "events": "【文化祭 (鯱光祭)】2026年9月26日(土)・27日(日) 一般公開<br>【学校説明会】2026年10月3日(土) / 2027年8月下旬",
    "url": "https://asahi-h.aichi-c.ed.jp/",
    "id": "asahi",
    "pageUrl": "schools/asahi.html"
  },
  {
    "rank": "S+",
    "rankClass": "rank-S-plus",
    "name": "東海高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市東区筒井",
    "group": "私立男子校（高校募集あり）",
    "score": "42〜45",
    "deviation": "72",
    "uniform": "セーラー/学ラン",
    "uniformDetail": "伝統の黒詰襟学ラン",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。ディベート部やワンダーフォーゲル部など全国屈指の強豪も多く活動は活発。",
    "features": "全国屈指の難関私立男子校。生徒の探究心と個性を尊重する自由な校風。仏教（浄土宗）精神。",
    "results": "国公立大学医学部合格者数は数十年間日本一。東大・京大・名大・旧帝大へ多数。",
    "events": "【記念祭 (文化祭)】2026年9月26日(土)・27日(日) 一般公開（予約不要）<br>【高校説明会】2026年10月17日(土)・11月7日(土)",
    "url": "https://www.tokai-jh.ed.jp/",
    "id": "tokai",
    "pageUrl": "schools/tokai.html"
  },
  {
    "rank": "S+",
    "rankClass": "rank-S-plus",
    "name": "明和高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市東区白壁",
    "group": "尾張2群 Aグループ",
    "score": "43〜45",
    "deviation": "70",
    "uniform": "セーラー/学ラン",
    "uniformDetail": "男子学ラン / 女子白襟セーラー服（スラックス選択可）",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年生は原則どこかの部活に登録。2年生以降は自由継続（多くの生徒が引退まで継続）。",
    "features": "旭丘と並ぶ名門校。附属中が設置され中高一貫が始動。SSH指定で探究活動が極めて盛ん。音楽科併設。",
    "results": "名古屋大学合格者数は県内トップ争い常連。国公立医学部・旧帝大・早慶へ多数。",
    "events": "【明和祭】2026年9月12日(土)・13日(日) 一般公開<br>【秋の学校見学会】2026年10月24日(土) / 2027年8月中旬",
    "url": "https://meiwa-h.aichi-c.ed.jp/",
    "id": "meiwa",
    "pageUrl": "schools/meiwa.html"
  },
  {
    "rank": "S+",
    "rankClass": "rank-S-plus",
    "name": "滝高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "江南市東野町",
    "group": "私立共学校（高校募集あり）",
    "score": "42〜44",
    "deviation": "71",
    "uniform": "ブレザー",
    "uniformDetail": "正統派濃紺ブレザー（ネクタイ/リボン）",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。勉強との両立を個人のペースで設計可能。週2〜3日活動の部も人気。",
    "features": "尾張北部の共学最高峰。緑豊かな広大なキャンパス。旭丘・一宮の併願先として多くの受験生が志望。",
    "results": "東大・京大・名大・医学部合格実績が抜群。早慶上智・理科大にも強い。",
    "events": "【滝学園祭】2026年9月19日(土)・20日(日)<br>【高校入試説明会】2026年10月10日(土)・11月14日(土)",
    "url": "https://www.taki-hy.ed.jp/",
    "id": "taki",
    "pageUrl": "schools/taki.html"
  },
  {
    "rank": "S+",
    "rankClass": "rank-S-plus",
    "name": "一宮高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "一宮市北園通",
    "group": "尾張1群 Aグループ（尾張共通）",
    "score": "42〜44",
    "deviation": "70",
    "uniform": "セーラー/学ラン",
    "uniformDetail": "男子学ラン / 女子セーラー服",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は原則全員加入。文武両道の気風が強く、8割以上の生徒が高2・高3まで精力的に活動。",
    "features": "尾張北部のトップ校。「ヤリ高」の愛称。文武両道の精神が徹底され、部活動や行事にも全力投球。",
    "results": "名古屋大学現役合格者数が全国トップクラス常連。京大・阪大など難関国公立へ多数。",
    "events": "【ヤリ高祭 (学校祭)】2026年9月11日(金)・12日(土)<br>【秋の体験入学】2026年10月17日(土) / 2027年8月下旬",
    "url": "https://ichinomiya-h.aichi-c.ed.jp/",
    "id": "ichinomiya",
    "pageUrl": "schools/ichinomiya.html"
  },
  {
    "rank": "S",
    "rankClass": "rank-S",
    "name": "向陽高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市昭和区広池町",
    "group": "尾張2群 Bグループ",
    "score": "41〜43",
    "deviation": "68",
    "uniform": "ブレザー",
    "uniformDetail": "男子学ラン / 女子紺ブレザー（チェック柄スカート）",
    "clubPolicy": "自由（任意）",
    "clubDetail": "加入は自由。ただし生徒の自発的加入率は90%以上と高く、オーケストラ部など活発。",
    "features": "桜通線「桜山駅」すぐ。明るくエネルギッシュな校風。「国際科学科」は科学・英語探究の最高峰。",
    "results": "名古屋大学をはじめ国公立大学へ多数進学。早慶・MARCH・関関同立にも強み。",
    "events": "【向陽祭】2026年9月11日(金)・12日(土) 一般公開<br>【学校見学会】2026年10月10日(土) / 2027年8月下旬",
    "url": "https://koyo-h.aichi-c.ed.jp/",
    "id": "koyo",
    "pageUrl": "schools/koyo.html"
  },
  {
    "rank": "S",
    "rankClass": "rank-S",
    "name": "菊里高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市名東区星が丘",
    "group": "尾張1群 Bグループ",
    "score": "40〜43",
    "deviation": "67",
    "uniform": "セーラー/学ラン",
    "uniformDetail": "男子学ラン / 女子一本ラインセーラー服",
    "clubPolicy": "自由（任意）",
    "clubDetail": "加入は任意。のびのびとした環境で、勉強・部活・習い事を両立する生徒が多い。",
    "features": "星ヶ丘駅徒歩5分。上品で穏やかな校風が女子を中心に大人気。旭丘の第2希望先。音楽科併設。",
    "results": "名大・名市大・愛知県立大などの地元国公立や南山大・早慶に安定した強さ。",
    "events": "【菊里祭】2026年9月11日(金)・12日(土) 一般公開<br>【学校見学会】2026年10月31日(土) / 2027年8月下旬",
    "url": "https://kikuzato-h.aichi-c.ed.jp/",
    "id": "kikuzato",
    "pageUrl": "schools/kikuzato.html"
  },
  {
    "rank": "S",
    "rankClass": "rank-S",
    "name": "愛知高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市千種区光が丘",
    "group": "私立共学校（選抜・普特）",
    "score": "38〜42",
    "deviation": "66",
    "uniform": "ブレザー",
    "uniformDetail": "トラディショナルな濃紺ブレザー",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。選抜クラスは学習優先で週日数の少ない部に入る生徒も多数。",
    "features": "仏教（曹洞宗）精神の文武両道校。規律と面倒見の良さ。公立トップ校の併願先として絶大な支持。",
    "results": "名大・名市大・名工大などの国公立大、早慶・MARCH・南山大学へ多数合格。",
    "events": "【愛知祭 (文化祭)】2026年9月19日(土)・20日(日)<br>【秋のオープンスクール】2026年10月17日(土)・11月7日(土)",
    "url": "https://aichi-h.ed.jp/",
    "id": "aichi",
    "pageUrl": "schools/aichi.html"
  },
  {
    "rank": "A+",
    "rankClass": "rank-A-plus",
    "name": "瑞陵高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市瑞穂区北原町",
    "group": "尾張2群 Aグループ",
    "score": "40〜42",
    "deviation": "66",
    "uniform": "セーラー/学ラン",
    "uniformDetail": "男子学ラン / 女子セーラー（選択制ブレザー導入）",
    "clubPolicy": "自由（任意）",
    "clubDetail": "加入は任意。自主自立の校風で運動部・文化部ともに生徒主体で活発に活動。",
    "features": "杉原千畝の母校。穏やかで自主性を重んじる校風。普通科のほか「理数科」「食物科」がある。",
    "results": "名古屋大学を中心とした国公立大学への現役合格実績が近年大きく躍進中。",
    "events": "【記念祭 (文化祭)】2026年9月11日(金)・12日(土)<br>【学校説明会】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://zuiryo-h.aichi-c.ed.jp/",
    "id": "zuiryo",
    "pageUrl": "schools/zuiryo.html"
  },
  {
    "rank": "A+",
    "rankClass": "rank-A-plus",
    "name": "千種高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市名東区社台",
    "group": "尾張2群 Bグループ",
    "score": "39〜42",
    "deviation": "66",
    "uniform": "私服",
    "uniformDetail": "私服通学OK（標準服あり・個性を尊重）",
    "clubPolicy": "自由（任意）",
    "clubDetail": "完全自由加入。ダンス部や英語系クラブなど自主性の高い活気あふれる部活動が揃う。",
    "features": "一社駅から徒歩圏の私服校。自主自立。「国際教養科」を設置し英語教育や海外研修が極めて充実。",
    "results": "国公立大学に加え、早慶・上智・ICU・MARCHや海外大学への進学者が多い。",
    "events": "【千種祭】2026年9月18日(金)・19日(土)<br>【学校説明会】2026年10月17日(土) / 2027年8月下旬",
    "url": "https://chigusa-h.aichi-c.ed.jp/",
    "id": "chigusa",
    "pageUrl": "schools/chigusa.html"
  },
  {
    "rank": "A+",
    "rankClass": "rank-A-plus",
    "name": "名古屋高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市東区砂田橋",
    "group": "私立男子校（文理選抜・文理）",
    "score": "38〜42",
    "deviation": "65",
    "uniform": "ブレザー",
    "uniformDetail": "濃紺ブレザー（スタイリッシュ）",
    "clubPolicy": "自由（任意）",
    "clubDetail": "希望制。サッカー部やテニス部など全国区の強豪も多く、設備も人工芝等でハイレベル。",
    "features": "砂田橋駅直結。キリスト教主義の男子進学校。近年、大学合格実績が愛知県私立トップ級に急伸。",
    "results": "名大などの難関国公立、早稲田・慶應・東京理科大・同志社大への合格数が激増。",
    "events": "【愛校祭 (文化祭)】2026年9月19日(土)・20日(日)<br>【高校入試説明会】2026年10月17日(土)・11月14日(土)",
    "url": "https://www.meigaku.ac.jp/",
    "id": "meigaku",
    "pageUrl": "schools/meigaku.html"
  },
  {
    "rank": "A+",
    "rankClass": "rank-A-plus",
    "name": "一宮西高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "一宮市日光町",
    "group": "尾張1群 Bグループ",
    "score": "39〜41",
    "deviation": "65",
    "uniform": "セーラー/学ラン",
    "uniformDetail": "男子学ラン / 女子セーラー服",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は原則加入。熱心な部活動指導と規律ある学校生活。",
    "features": "一宮高校の併願先として尾張北部で高い信頼。勉強に対する熱心な指導と高い進学意欲。",
    "results": "名古屋大・名工大・岐阜大・三重大など東海地方の国公立大へ抜群の合格率。",
    "events": "【西高祭】2026年9月10日(木)・11日(金)<br>【体験入学】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://ichinomiyanishi-h.aichi-c.ed.jp/",
    "id": "ichinomiya-nishi",
    "pageUrl": "schools/ichinomiya-nishi.html"
  },
  {
    "rank": "A",
    "rankClass": "rank-A",
    "name": "名城大学附属高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市中村区新富町",
    "group": "私立共学校（特進・進学・理数・総合）",
    "score": "35〜41",
    "deviation": "63",
    "uniform": "ブレザー",
    "uniformDetail": "現代的で洗練されたブレザー",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。運動部・文化部ともに施設が充実しており高い加入率。",
    "features": "名城大学直結。理数・薬学・情報系の最新設備。名城大への内部推薦枠が極めて厚く大人気。",
    "results": "名城大学へ多数推薦進学。特進・理数からは国公立大学や南山大へも多数。",
    "events": "【名城祭】2026年9月26日(土)・27日(日)<br>【学校説明会】2026年10月17日(土)・11月7日(土)",
    "url": "https://www.meijo-h.ed.jp/",
    "id": "meijo",
    "pageUrl": "schools/meijo.html"
  },
  {
    "rank": "A",
    "rankClass": "rank-A",
    "name": "桜台高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市南区霞町",
    "group": "尾張1群 Bグループ",
    "score": "37〜40",
    "deviation": "63",
    "uniform": "ブレザー",
    "uniformDetail": "正統派ネイビーブレザー",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は全員加入。部活動加入率は学校全体で9割を超え、非常に熱心な文武両道。",
    "features": "部活動加入率が高く文武両道。「ファッション創造科」も併設。堅実で親身な進路指導。",
    "results": "名大・名工大・愛知県立大などの国公立大学や南山大学・名城大学に手堅い実績。",
    "events": "【桜台祭】2026年9月18日(金)・19日(土)<br>【学校説明会】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://sakuradai-h.aichi-c.ed.jp/",
    "id": "sakuradai",
    "pageUrl": "schools/sakuradai.html"
  },
  {
    "rank": "A",
    "rankClass": "rank-A",
    "name": "名東高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市名東区神里",
    "group": "尾張2群 Aグループ",
    "score": "37〜40",
    "deviation": "63",
    "uniform": "ブレザー",
    "uniformDetail": "爽やかなブレザースタイル",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は原則加入。英語ディベート部や運動部など明るく活発な部が多い。",
    "features": "「国際英語科」がありグローバル教育に注力。生徒が主体で明るく活気のある学校行事。",
    "results": "南山大学・名城大学などの地元上位私大、国公立大学へバランスよく進学。",
    "events": "【名東祭】2026年9月18日(金)・19日(土)<br>【秋の体験入学】2026年10月17日(土) / 2027年8月下旬",
    "url": "https://meito-h.aichi-c.ed.jp/",
    "id": "meito",
    "pageUrl": "schools/meito.html"
  },
  {
    "rank": "A",
    "rankClass": "rank-A",
    "name": "中京大学附属中京高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市昭和区川名山町",
    "group": "私立共学校（特進・進学・国際）",
    "score": "35〜40",
    "deviation": "62",
    "uniform": "ブレザー",
    "uniformDetail": "高い人気を誇るデザインブレザー",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。全国大会レベルの強化指定部からエンジョイ系の部まで多彩。",
    "features": "甲子園やスケートで全国区のスポーツ強豪校。中京大学への接続枠が強い。特進は国公立大志向。",
    "results": "中京大学への内部進学多数。特進クラスから難関国公立大学・早慶へ進学。",
    "events": "【中京祭】2026年9月26日(土)・27日(日)<br>【入試説明会】2026年10月24日(土)・11月14日(土)",
    "url": "https://www.chukyo.ed.jp/",
    "id": "chukyo",
    "pageUrl": "schools/chukyo.html"
  },
  {
    "rank": "A",
    "rankClass": "rank-A",
    "name": "横須賀高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "東海市高横須賀町",
    "group": "知多・尾張2群 Aグループ",
    "score": "36〜39",
    "deviation": "63",
    "uniform": "セーラー/学ラン",
    "uniformDetail": "男子学ラン / 女子セーラー服",
    "clubPolicy": "全員必須",
    "clubDetail": "原則全員部活動加入制。伝統的に文武両道を重んじ、学習と部活動の両立を推進。",
    "features": "知多地区のトップ伝統校。真面目で学習熱心な生徒が集まる。手厚い学習サポート。",
    "results": "名古屋大学・名工大・愛知県立大などの国公立大学へ高い進学率を誇る。",
    "events": "【横高祭】2026年9月11日(金)・12日(土)<br>【体験入学】2026年10月31日(土) / 2027年8月下旬",
    "url": "https://yokosuka-h.aichi-c.ed.jp/",
    "id": "yokosuka",
    "pageUrl": "schools/yokosuka.html"
  },
  {
    "rank": "B+",
    "rankClass": "rank-B-plus",
    "name": "昭和高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市瑞穂区玉水町",
    "group": "尾張2群 Aグループ",
    "score": "36〜38",
    "deviation": "62",
    "uniform": "セーラー/学ラン",
    "uniformDetail": "男子学ラン / 女子濃紺セーラー服",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は原則加入。温厚な生徒が多くアットホームな部活動が多い。",
    "features": "閑静な文教エリア。温厚で真面目な校風。生徒一人ひとりを大切にする落ち着いた環境。",
    "results": "愛知県立大・名市大などの国公立大、南山大学、名城大学へ多数合格。",
    "events": "【昭和祭】2026年9月18日(金)・19日(土)<br>【秋の体験入学】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://showa-h.aichi-c.ed.jp/",
    "id": "showa",
    "pageUrl": "schools/showa.html"
  },
  {
    "rank": "B+",
    "rankClass": "rank-B-plus",
    "name": "松蔭高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市中村区烏森町",
    "group": "尾張1群 Bグループ",
    "score": "35〜38",
    "deviation": "61",
    "uniform": "ブレザー",
    "uniformDetail": "新デザインの人気スタイリッシュブレザー",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は全員加入。和太鼓部やダンス部、各種運動部が非常に盛んで加入率高。",
    "features": "烏森駅すぐ・名駅から好アクセス。ダンス部をはじめ部活動が盛んで行事の熱気は随一。",
    "results": "南山大・名城大・中京大・愛知大（SSALL）への進学が中心。国公立大進学も伸長。",
    "events": "【松蔭祭】2026年9月18日(金)・19日(土)<br>【学校説明会】2026年10月17日(土) / 2027年8月下旬",
    "url": "https://shoin-h.aichi-c.ed.jp/",
    "id": "shoin",
    "pageUrl": "schools/shoin.html"
  },
  {
    "rank": "B+",
    "rankClass": "rank-B-plus",
    "name": "名古屋南高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市南区桜本町",
    "group": "尾張1群 Aグループ",
    "score": "35〜38",
    "deviation": "61",
    "uniform": "ブレザー",
    "uniformDetail": "端正な濃紺ブレザー",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は原則加入。平日の活動時間を適切に抑え、補習・学習との両立を徹底。",
    "features": "地下鉄桜本町駅すぐ。手厚い補習と親身な進路相談で国公立大学進学をサポート。",
    "results": "名工大・愛知県立大・三重大などの国公立大、南山大・名城大へ安定した実績。",
    "events": "【南高祭】2026年9月18日(金)・19日(土)<br>【体験入学】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://nagoyaminami-h.aichi-c.ed.jp/",
    "id": "nagoya-minami",
    "pageUrl": "schools/nagoya-minami.html"
  },
  {
    "rank": "B+",
    "rankClass": "rank-B-plus",
    "name": "椙山女学園高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市千種区山添町",
    "group": "私立女子校（高校募集あり）",
    "score": "33〜36",
    "deviation": "60",
    "uniform": "セーラー/学ラン",
    "uniformDetail": "伝統の白襟セーラー服",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。フィルハーモニーやダンス、テニスなど華やかで活発なクラブ多数。",
    "features": "名古屋の伝統ある名門女子校。手厚い情操教育。椙山女学園大学への内部進学枠が豊富。",
    "results": "椙山女学園大学（生活科学部・教育学部・看護など）へ多数推薦進学。",
    "events": "【椙山祭】2026年9月26日(土)・27日(日)<br>【秋の見学会・相談会】2026年10月24日(土)・11月14日(土)",
    "url": "https://www.sugiyama-u.ac.jp/high/",
    "id": "sugiyama",
    "pageUrl": "schools/sugiyama.html"
  },
  {
    "rank": "B+",
    "rankClass": "rank-B-plus",
    "name": "愛知工業大学名電高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市千種区若水",
    "group": "私立共学校（普特・進学・科学技術・情報）",
    "score": "34〜38",
    "deviation": "60",
    "uniform": "ブレザー",
    "uniformDetail": "現代的な濃紺ブレザー",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入。吹奏楽部やメカトロニクス部など全国トップの強豪部は猛練習あり。",
    "features": "吹奏楽部や野球部、メカトロニクスで全国屈指の強豪。愛知工業大学への直結推薦枠が魅力。",
    "results": "愛知工業大学へ多数内部進学。特進クラスから国公立・難関理工系大学へ合格。",
    "events": "【名電祭】2026年9月26日(土)・27日(日)<br>【オープンスクール】2026年10月10日(土)・11月7日(土)",
    "url": "https://www.meiden.ed.jp/",
    "id": "meiden",
    "pageUrl": "schools/meiden.html"
  },
  {
    "rank": "B",
    "rankClass": "rank-B",
    "name": "天白高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市天白区植田",
    "group": "尾張2群 Bグループ",
    "score": "33〜36",
    "deviation": "58",
    "uniform": "ブレザー",
    "uniformDetail": "ベーシックなブレザースタイル",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は全員加入。広いグラウンドを活用した球技系や文化部が盛ん。",
    "features": "自然豊かな丘陵地に位置する穏やかな校風。勉強と部活動を両立しやすい環境。",
    "results": "南山大・中京大・名城大・愛知大など地元有名私大を中心に多数合格。",
    "events": "【天白祭】2026年9月18日(金)・19日(土)<br>【体験入学】2026年10月31日(土) / 2027年8月下旬",
    "url": "https://tempaku-h.aichi-c.ed.jp/",
    "id": "tempaku",
    "pageUrl": "schools/tempaku.html"
  },
  {
    "rank": "B",
    "rankClass": "rank-B",
    "name": "熱田高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市熱田区神宮",
    "group": "尾張1群 Aグループ",
    "score": "32〜35",
    "deviation": "56",
    "uniform": "ブレザー",
    "uniformDetail": "ブレザースタイル",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は原則加入。サッカー部・吹奏楽部など強豪部活を中心に高い熱気。",
    "features": "熱田神宮すぐ。サッカー部や吹奏楽部など強豪部活が目白押し。私大指定校推薦枠多数。",
    "results": "中京大、名城大、愛知学院大、愛知大などの地元私立大学へ多数進学。",
    "events": "【熱高祭】2026年9月18日(金)・19日(土)<br>【体験入学】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://atsuta-h.aichi-c.ed.jp/",
    "id": "atsuta",
    "pageUrl": "schools/atsuta.html"
  },
  {
    "rank": "B",
    "rankClass": "rank-B",
    "name": "東邦高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市名東区平和が丘",
    "group": "私立共学校（文理・普通・人間健康・美術）",
    "score": "31〜35",
    "deviation": "56",
    "uniform": "ブレザー",
    "uniformDetail": "洗練された現代風ブレザー",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。野球部やマーチングなど全国区の部活から趣味系まで選択肢豊富。",
    "features": "甲子園優勝の野球部・マーチングバンド部など部活動が極めて活発。校舎が綺麗で人気。",
    "results": "愛知東邦大学への内部推薦、中京大・名城大・愛知学院大・中部大などへの進学多数。",
    "events": "【東邦祭】2026年9月26日(土)・27日(日)<br>【入試説明会】2026年10月24日(土)・11月14日(土)",
    "url": "https://www.toho-h.ed.jp/",
    "id": "toho",
    "pageUrl": "schools/toho.html"
  },
  {
    "rank": "B",
    "rankClass": "rank-B",
    "name": "名経大高蔵高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市瑞穂区高田町",
    "group": "私立共学校（特進・進学・商）",
    "score": "31〜35",
    "deviation": "55",
    "uniform": "ブレザー",
    "uniformDetail": "チェック柄スカート/スラックスのブレザー",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。女子サッカー部やカラーガード部など全国レベルの部も存在。",
    "features": "桜山駅・金山駅から通学便利。手厚い個別指導と進路サポート。商業科もあり資格取得に強み。",
    "results": "名古屋経済大学への内部進学、愛知学院大・中京大・名城大などへ進学。",
    "events": "【高蔵祭】2026年9月26日(土)・27日(日)<br>【学校説明会】2026年10月17日(土)・11月7日(土)",
    "url": "https://www.nagoya-ku.ac.jp/takakura-h/",
    "id": "takakura",
    "pageUrl": "schools/takakura.html"
  },
  {
    "rank": "C+",
    "rankClass": "rank-C-plus",
    "name": "日進西高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "日進市浅田町",
    "group": "尾張2群 Bグループ",
    "score": "29〜33",
    "deviation": "53",
    "uniform": "ブレザー",
    "uniformDetail": "ブレザースタイル",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は原則加入。温厚な生徒が多く、無理のないペースで部活に参加可能。",
    "features": "赤池駅からアクセス良好。真面目で温厚な校風。ICTを活用した授業を推進。",
    "results": "愛知淑徳大・金城学院大・愛知学院大・名城大・中京大などに進学。",
    "events": "【西高祭】2026年9月18日(金)・19日(土)<br>【体験入学】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://nisshin-w-h.aichi-c.ed.jp/",
    "id": "nisshin-nishi",
    "pageUrl": "schools/nisshin-nishi.html"
  },
  {
    "rank": "C+",
    "rankClass": "rank-C-plus",
    "name": "長久手高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "長久手市坊の後",
    "group": "尾張2群 Aグループ",
    "score": "28〜32",
    "deviation": "51",
    "uniform": "セーラー/学ラン",
    "uniformDetail": "男子学ラン / 女子セーラー服",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は原則加入。運動部を中心に元気に活動。",
    "features": "リニモ沿線。自然に囲まれた広いグラウンド。医療看護コースを設置し進路直結指導。",
    "results": "愛知学院大学・中部大学・名古屋学院大学・看護系専門学校などへ多数進学。",
    "events": "【長高祭】2026年9月18日(金)・19日(土)<br>【体験入学】2026年10月31日(土) / 2027年8月下旬",
    "url": "https://nagakute-h.aichi-c.ed.jp/",
    "id": "nagakute",
    "pageUrl": "schools/nagakute.html"
  },
  {
    "rank": "C+",
    "rankClass": "rank-C-plus",
    "name": "東川端（大同大学大同）",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市南区大同町",
    "group": "私立共学校（特進・進学・情報・機械）",
    "score": "28〜33",
    "deviation": "51",
    "uniform": "ブレザー",
    "uniformDetail": "落ち着いた濃紺ブレザー",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。ものづくり・ロボット系や各種スポーツ部など多彩。",
    "features": "大同町駅すぐ。大同特殊鋼グループのバックボーン。工業・情報教育が手厚く就職・進学両立。",
    "results": "大同大学への内部推薦進学、大手製造業への高い就職実績。",
    "events": "【大同祭】2026年10月3日(土)・4日(日)<br>【入試体験会】2026年10月24日(土)・11月14日(土)",
    "url": "https://www.daido-h.ed.jp/",
    "id": "daido",
    "pageUrl": "schools/daido.html"
  },
  {
    "rank": "C+",
    "rankClass": "rank-C-plus",
    "name": "至学館高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市東区矢田南",
    "group": "私立共学校（普通・アドバンス・スポーツ・商業）",
    "score": "27〜31",
    "deviation": "50",
    "uniform": "ブレザー",
    "uniformDetail": "チェック柄を取り入れた明るいブレザー",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。女子レスリングや硬式野球部など全国屈指の超強豪部あり。",
    "features": "ナゴヤドーム前矢田駅すぐ。女子レスリングや野球などスポーツ名門。至学館大学への接続。",
    "results": "至学館大学、愛知学院大、名古屋学院大、東海学園大、専門学校へ多数。",
    "events": "【至学館祭】2026年9月26日(土)・27日(日)<br>【説明体験会】2026年10月17日(土)・11月7日(土)",
    "url": "https://www.shigakkan-h.ed.jp/",
    "id": "shigakkan",
    "pageUrl": "schools/shigakkan.html"
  },
  {
    "rank": "C",
    "rankClass": "rank-C",
    "name": "鳴海高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市緑区左京山",
    "group": "尾張1群 Aグループ",
    "score": "26〜29",
    "deviation": "48",
    "uniform": "ブレザー",
    "uniformDetail": "ブレザースタイル",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は原則加入。初心者歓迎の部活動が多く馴染みやすい。",
    "features": "名鉄左京山駅徒歩5分。落ち着いた環境で、基礎からの学び直しと生活指導を徹底。",
    "results": "愛知学院大・東海学園大・名古屋学院大・各種専門学校・公務員など。",
    "events": "【鳴高祭】2026年9月18日(金)・19日(土)<br>【体験入学】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://narumi-h.aichi-c.ed.jp/",
    "id": "narumi",
    "pageUrl": "schools/narumi.html"
  },
  {
    "rank": "C",
    "rankClass": "rank-C",
    "name": "山田高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市西区山田町",
    "group": "尾張2群 Aグループ",
    "score": "26〜29",
    "deviation": "47",
    "uniform": "ブレザー",
    "uniformDetail": "ブレザースタイル",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は原則加入。放課後の時間を部活と仲間づくりに活用。",
    "features": "庄内緑地公園駅近く。部活動が盛んでアットホームな雰囲気。一人ひとりに寄り添う指導。",
    "results": "名古屋学院大・同朋大・愛知東邦大・専門学校・就職など幅広い進路。",
    "events": "【山高祭】2026年9月18日(金)・19日(土)<br>【体験入学】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://yamada-h.aichi-c.ed.jp/",
    "id": "yamada",
    "pageUrl": "schools/yamada.html"
  },
  {
    "rank": "C",
    "rankClass": "rank-C",
    "name": "名古屋経済大市邨高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市千種区北千種",
    "group": "私立共学校（ブライト・アカデミック・エクスプローラー）",
    "score": "26〜31",
    "deviation": "48",
    "uniform": "ブレザー",
    "uniformDetail": "デザイナーズブランドのおしゃれな制服",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。バドミントンやテニス、軽音、探究サークルなど多彩。",
    "features": "探究型学習やICT教育（1人1台PC活用）を先進的に導入。生徒の自由な個性を伸ばす指導。",
    "results": "名古屋経済大学への内部推薦、愛知学院大、名古屋外国語大、専門学校多数。",
    "events": "【市邨祭】2026年9月26日(土)・27日(日)<br>【入試説明会】2026年10月24日(土)・11月14日(土)",
    "url": "https://ichimura.ed.jp/",
    "id": "ichimura",
    "pageUrl": "schools/ichimura.html"
  },
  {
    "rank": "C",
    "rankClass": "rank-C",
    "name": "同朋高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市中村区稲葉地町",
    "group": "私立共学校（普通・音楽・美術）",
    "score": "25〜29",
    "deviation": "47",
    "uniform": "ブレザー",
    "uniformDetail": "モダンなブレザー",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。音楽・美術系クラブの活動水準が非常に高い。",
    "features": "音楽科・美術科を設置する芸術系名門。多様性を認め合う温かい校風。同朋大学直結。",
    "results": "同朋大学・名古屋造形大学・名古屋音楽大学への内部進学、各種美大・私立大。",
    "events": "【同朋祭】2026年9月26日(土)・27日(日)<br>【体験入学】2026年10月17日(土)・11月7日(土)",
    "url": "https://www.doho.ed.jp/",
    "id": "doho",
    "pageUrl": "schools/doho.html"
  },
  {
    "rank": "D+",
    "rankClass": "rank-D-plus",
    "name": "緑高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市緑区旭出",
    "group": "尾張2群 Bグループ",
    "score": "23〜26",
    "deviation": "44",
    "uniform": "ブレザー",
    "uniformDetail": "スタンダードなブレザー",
    "clubPolicy": "1年次必須",
    "clubDetail": "1年次は全員加入。運動部・文化部ともに活動しやすい環境。",
    "features": "緑豊かな環境。少人数指導や習熟度別授業を取り入れ、基礎学力の定着に注力。",
    "results": "東海学園大学、中部大学、愛知工科大学、専門学校進学、地元企業就職。",
    "events": "【緑高祭】2026年9月18日(金)・19日(土)<br>【体験入学】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://midori-h.aichi-c.ed.jp/",
    "id": "midori",
    "pageUrl": "schools/midori.html"
  },
  {
    "rank": "D+",
    "rankClass": "rank-D-plus",
    "name": "享栄高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市瑞穂区汐路町",
    "group": "私立共学校（特進・躍進・機械・商業）",
    "score": "22〜26",
    "deviation": "43",
    "uniform": "ブレザー",
    "uniformDetail": "グレー基調の洗練ブレザー",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。硬式野球部など強豪を目指す生徒も、資格取得に専念する生徒も自由。",
    "features": "甲子園出場多数の硬式野球部名門。資格取得サポートや就職支援が極めて手厚い。",
    "results": "鈴鹿医療科学大、愛知学院大、大手自動車・重工関連企業への就職多数。",
    "events": "【栄祭】2026年10月3日(土)・4日(日)<br>【学校説明会】2026年10月17日(土)・11月14日(土)",
    "url": "https://www.kyoei-h.ed.jp/",
    "id": "kyoei",
    "pageUrl": "schools/kyoei.html"
  },
  {
    "rank": "D+",
    "rankClass": "rank-D-plus",
    "name": "名古屋大谷高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市瑞穂区高田町",
    "group": "私立共学校（特進・普通・福祉）",
    "score": "22〜26",
    "deviation": "43",
    "uniform": "ブレザー",
    "uniformDetail": "ブレザースタイル（清楚）",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。ボランティア・福祉系サークルや各種運動部あり。",
    "features": "真宗大谷派の教えに基づく命の教育。福祉コースでは介護職員初任者研修の資格取得が可能。",
    "results": "大谷大学、同朋大学、愛知文教大学、医療・福祉系専門学校、福祉施設就職。",
    "events": "【洗心祭】2026年9月26日(土)・27日(日)<br>【入試相談会】2026年10月24日(土)・11月14日(土)",
    "url": "https://www.nagoyaotani.ed.jp/",
    "id": "nagoya-otani",
    "pageUrl": "schools/nagoya-otani.html"
  },
  {
    "rank": "D",
    "rankClass": "rank-D",
    "name": "守山高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "名古屋市守山区緑ヶ丘",
    "group": "尾張1群 Aグループ",
    "score": "19〜22",
    "deviation": "40",
    "uniform": "ブレザー",
    "uniformDetail": "ブレザースタイル",
    "clubPolicy": "自由（任意）",
    "clubDetail": "加入は任意。無理なく参加できる部活が多く、アルバイト等と両立する生徒も。",
    "features": "名古屋市内の公立普通科で最も入りやすいラインの一つ。少人数での学び直し授業や丁寧な生活指導。",
    "results": "愛知産業大学、東海学院大学、自動車・調理・理美容系専門学校、民間企業就職。",
    "events": "【守高祭】2026年9月18日(金)・19日(土)<br>【秋の体験入学】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://moriyama-h.aichi-c.ed.jp/",
    "id": "moriyama",
    "pageUrl": "schools/moriyama.html"
  },
  {
    "rank": "D",
    "rankClass": "rank-D",
    "name": "春日井泉高等学校",
    "type": "public",
    "typeLabel": "公立",
    "location": "春日井市西山町",
    "group": "総合学科・専門学科",
    "score": "18〜22",
    "deviation": "39",
    "uniform": "ブレザー",
    "uniformDetail": "ブレザースタイル",
    "clubPolicy": "自由（任意）",
    "clubDetail": "加入は任意。専門学科の実習や資格取得の勉強に時間を使う生徒が多い。",
    "features": "生活文化科やITビジネスなど多彩な系列から自分の進路を選べる。実務・資格取得に特化。",
    "results": "各種専門学校、地元一般企業・サービス業就職、私立短期大学。",
    "events": "【泉高祭】2026年10月3日(土)<br>【秋の体験入学】2026年10月24日(土) / 2027年8月下旬",
    "url": "https://kasugaiizumi-h.aichi-c.ed.jp/",
    "id": "kasugai-izumi",
    "pageUrl": "schools/kasugai-izumi.html"
  },
  {
    "rank": "D",
    "rankClass": "rank-D",
    "name": "菊華高等学校",
    "type": "private",
    "typeLabel": "私立",
    "location": "名古屋市守山区小幡",
    "group": "私立共学校（普通・福祉・情報・保育）",
    "score": "18〜22",
    "deviation": "39",
    "uniform": "ブレザー",
    "uniformDetail": "ブレザースタイル",
    "clubPolicy": "自由（任意）",
    "clubDetail": "自由加入制。専門コースの勉強や実習、アルバイトとの両立がしやすい。",
    "features": "保育・福祉・情報ITなど専門コースが豊富。基礎から徹底的に指導し、就職や進学を全面バックアップ。",
    "results": "系列専門学校、愛知産業大、名古屋産業大、保育所・福祉施設・地元企業就職。",
    "events": "【菊華祭】2026年10月17日(土)・18日(日)<br>【オープンスクール】2026年10月24日(土)・11月14日(土)",
    "url": "https://www.kikuka.ed.jp/",
    "id": "kikuka",
    "pageUrl": "schools/kikuka.html"
  },
  {
    "rank": "E",
    "rankClass": "rank-E",
    "name": "東邦高校 (単位制・通信等) / サポート校",
    "type": "private",
    "typeLabel": "私立/通信",
    "location": "名古屋市内各所",
    "group": "通信制・単位制コース（入試選抜）",
    "score": "14〜18",
    "deviation": "36",
    "uniform": "私服",
    "uniformDetail": "私服登校可（登校日数選択可能）",
    "clubPolicy": "自由（任意）",
    "clubDetail": "完全自由。サークル活動等への参加は自由意思で負担なし。",
    "features": "不登校経験者や自分のペースで高校卒業資格を取得したい生徒を支える柔軟な教育環境。",
    "results": "提携大学・短大への推薦進学、各種クリエイティブ系専門学校、自立就労支援。",
    "events": "【個別学校説明会】毎月開催（随時見学可能・要予約）",
    "url": "https://www.toho-h.ed.jp/",
    "id": "toho-tsushin",
    "pageUrl": "schools/toho-tsushin.html"
  }
];

if (typeof module !== 'undefined') {
  module.exports = schoolsData;
}
